# Generated by Django 4.1.1 on 2022-09-15 17:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pytz
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('paintingMuse', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='PaintingMutation',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('prompt', models.CharField(max_length=600)),
        #         ('request_date', models.DateTimeField(default=datetime.now(pytz.utc), verbose_name='date published')),
        #     ],
        # ),
        migrations.AddField(
            model_name='painting',
            name='created_at',
            field=models.DateTimeField(default=datetime.now(pytz.utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painting',
            name='title',
            field=models.CharField(default="Untitled", max_length=280),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painting',
            name='prompt',
            field=models.CharField(default="", max_length=700),
            preserve_default=False,
        ),
        # migrations.AddField(
        #     model_name='painting',
        #     name='mutation',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintingMuse.paintingmutation'),
        #     preserve_default=False,
        # ),
    ]
