# Generated by Django 4.1.1 on 2022-09-15 17:41

import datetime
from django.db import migrations, models
import django.utils.timezone
from datetime import datetime
import pytz


class Migration(migrations.Migration):

    dependencies = [
        ('paintingMuse', '0002_paintingmutation_painting_created_at_painting_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintingmutation',
            name='request_date',
            field=models.DateTimeField(default=datetime.now(pytz.utc), verbose_name='date published'),
        ),
    ]
