# Generated by Django 4.1.1 on 2022-09-15 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paintingMuse', '0003_alter_paintingmutation_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        # migrations.AlterField(
        #     model_name='paintingmutation',
        #     name='request_date',
        #     field=models.DateTimeField(verbose_name='date published'),
        # ),
    ]
