# Generated by Django 4.1.1 on 2022-09-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintingMuse', '0004_painting_user_alter_paintingmutation_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='image_url',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
