# Generated by Django 4.1.1 on 2022-09-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintingMuse', '0005_painting_image_url'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='painting',
        #     name='prompt',
        # ),
        migrations.AlterField(
            model_name='painting',
            name='artist_id',
            field=models.CharField(editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='painting',
            name='inspiration_image_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
