# Generated by Django 4.1.1 on 2022-09-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintingMuse', '0006_remove_painting_prompt_alter_painting_artist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='artist_id',
            field=models.CharField(editable=False, max_length=12),
        ),
    ]
