# Generated by Django 4.1.1 on 2022-09-16 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paintingMuse', '0007_painting_height_painting_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='inspiration_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Player who created the painting.'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
